---
stages:
  - linting
  - docs

ruff-format:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff --version
    - ruff format --check --diff

ruff-check:
  stage: linting
  image: registry.gitlab.com/pipeline-components/ruff:latest
  script:
    - ruff --version
    - ruff check

pages:
  stage: docs
  image: python
  artifacts:
    paths:
      - public
  script:
    - pip install -r docs/requirements.txt
    - pip install .
    - mkdocs build -d public
    - echo $CI_PAGES_URL
