[project]
name = "{{ cookiecutter.project_slug }}"
description = "{{ cookiecutter.project_short_description }}"
version = "{{ cookiecutter.version }}"
readme = "README.md"
authors = [
  {name = "{{ cookiecutter.author }}", email = "{{ cookiecutter.email }}"},
]
maintainers = [
  {name = "{{ cookiecutter.author }}", email = "{{ cookiecutter.email }}"},
]
requires-python = ">=3.13"
dependencies = [
    "wheel>=0.45.1",
]

[project.scripts]
{{ cookiecutter.project_slug }} = "{{ cookiecutter.project_slug }}.{{ cookiecutter.project_slug }}:main"

[dependency-groups]
lint = [
    "ruff>=0.11.13",
]
doc = [
    "mkdocs-material>=9.6.14",
    "mkdocstrings[python]>=0.29.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100 # higher line-length since black sometimes ignores lines >88

[tool.ruff.lint]
select = [ 
#   "D", # PyDocStyle
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I", # isort (missing/unsorted imports)
    "B", # Bugbear
    "YTT", # Flake8-2020
    "S", # flake8-bandit
    "C4",# flake8-comprehensions
    "F", # PyFlakes
    "UP", # pyupgrade
    "RUF", # ruff   
    "TRY" # tryceratops
]

# only fix unsorted imports and trailing whitespace with --fix
fixable = [ "ALL" ]

[tool.ruff.lint.pydocstyle]
# add "D" to selected/fixable rules to enforce this
convention = "numpy"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

