[project]
name = "{{ cookiecutter.project_slug }}"
description = "{{ cookiecutter.project_short_description }}"
version = "{{ cookiecutter.version }}"
dependencies = []
readme = "README.md"
authors = [
  {name = "{{ cookiecutter.author }}", email = "{{ cookiecutter.email }}"},
]
maintainers = [
  {name = "{{ cookiecutter.author }}", email = "{{ cookiecutter.email }}"},
]

[project.scripts]
{{ cookiecutter.project_slug }} = "{{ cookiecutter.project_slug }}.{{ cookiecutter.project_slug }}:main"

[project.optional-dependencies]
dev = [
    "nox",
    "ruff",
    "bump-my-version",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.ruff]
line-length = 100 # higher line-length since black sometimes ignores lines >88

[tool.ruff.lint]
select = [ 
    "E", # pycodestyle errors
    "W", # pycodestyle warnings
    "F", # pyflakes
    "I"  # isort (missing/unsorted imports)
]

# only fix unsorted imports and trailing whitespace with --fix
fixable = [ "I001", "W291" ]

[tool.ruff.lint.pydocstyle]
# add "D" to selected/fixable rules to enforce this
convention = "numpy"

[tool.ruff.format]
# Like Black, use double quotes for strings.
quote-style = "double"
# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

